### ISSUE TITLE
enable plugin when already in copy mode and scrolled around

### ISSUE THREAD

**Issue by Lgggg** [schasse/tmux-jump#11] opened 2019-12-21 11:10 UTC
please help~

**Comment by Lgggg** [comment] 2019-12-21 17:24
it jump to the bottom when wake up this plugin

**Comment by schasse** [comment] 2019-12-23 09:37
Hey, this is currently not possible. I keep this on the todo list.

**Comment by Lgggg** [comment] 2019-12-23 10:01
thank~ I like your plugin very much~

**Comment by schasse** [comment] 2019-12-29 10:10
duplicate of https://github.com/schasse/tmux-easymotion/issues/4

**Closed as completed by schasse** 2019-12-29 10:10 UTC
